name: socket_mobile
description: Socket Mobile Capture SDK
version: 0.0.1
homepage: https://github.com/jonathantribouharet/flutter_socket_mobile

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  equatable: any
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: co.eivo.socket_mobile
        pluginClass: SocketMobilePlugin
      ios:
        pluginClass: SocketMobilePlugin
